CREATE TABLE TWSS_FOLLOWERS(
	ID NUMBER NOT NULL,
	UUID VARCHAR2(250 BYTE) NOT NULL,
	SENDER_USERNAME VARCHAR2(250 BYTE) NOT NULL,
    RECEIVER_USERNAME VARCHAR2(250 BYTE) NOT NULL,
	STATE NUMBER(1,0) NOT NULL,
    CREATED TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    MODIFIED TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT TWSS_FOLLOWERS_PK PRIMARY KEY (ID) ENABLE,
    CONSTRAINT TWSS_FOLLOWERS_UUID_UQ UNIQUE (UUID),
    CONSTRAINT TWSS_FOLLOWERS_USRS_UQ UNIQUE (SENDER_USERNAME, RECEIVER_USERNAME)
);


CREATE SEQUENCE TWSS_FOLLOWERS_SEQ;
 
CREATE TRIGGER TWSS_FOLLOWERS_TRG
BEFORE INSERT ON TWSS_FOLLOWERS
FOR EACH ROW
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT TWSS_FOLLOWERS_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/