CREATE TABLE TWSS_CHAT_MESSAGES(
	ID NUMBER NOT NULL,
	SENDER_USERNAME VARCHAR2(250 BYTE) NOT NULL,
    RECEIVER_USERNAME VARCHAR2(250 BYTE) NOT NULL,
    MESSAGE VARCHAR2(2000 BYTE) NOT NULL,
	VIEWED NUMBER(1,0) NOT NULL,
    CREATED TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT TWSS_CHAT_MESSAGES_PK PRIMARY KEY (ID) ENABLE
);

create index TWSS_CHAT_MESSAGES_IDX 
on TWSS_CHAT_MESSAGES ( SENDER_USERNAME, RECEIVER_USERNAME);

CREATE SEQUENCE TWSS_CHAT_MESSAGES_SEQ;
 
CREATE TRIGGER TWSS_CHAT_MESSAGES_TRG
BEFORE INSERT ON TWSS_CHAT_MESSAGES
FOR EACH ROW
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT TWSS_CHAT_MESSAGES_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/