CREATE TABLE TWSS_NOTIFICATIONS(
	ID NUMBER NOT NULL,
	TYPE VARCHAR2(250 BYTE) NOT NULL,
	RECEIVER_USERNAME VARCHAR2(250 BYTE) NOT NULL,
	SENDER_USERNAME VARCHAR2(250 BYTE) NOT NULL,
	SENDER_NAME VARCHAR2(250 BYTE) NOT NULL,
	SENDER_PICTURE VARCHAR2(250 BYTE) NULL,
	VIEWED NUMBER(1,0) NOT NULL,
	OPENED NUMBER(1,0) NOT NULL,
    CREATED TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT TWSS_NOTIFICATIONS_PK PRIMARY KEY (ID) ENABLE
);

CREATE SEQUENCE TWSS_NOTIFICATIONS_SEQ;
 
CREATE TRIGGER TWSS_NOTIFICATIONS_TRG
BEFORE INSERT ON TWSS_NOTIFICATIONS
FOR EACH ROW
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT TWSS_NOTIFICATIONS_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/