CREATE TABLE TWSS_POSTS(
	ID NUMBER NOT NULL,
	UUID VARCHAR2(250 BYTE) NOT NULL,
	TYPE VARCHAR2(250 BYTE) NOT NULL,
	USERNAME VARCHAR2(250 BYTE) NOT NULL,
	TEXT VARCHAR2(3000 BYTE) NOT NULL,
	UUID_PARENT VARCHAR2(250 BYTE) NULL,
    CREATED TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    MODIFIED TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT TWSS_POSTS_PK PRIMARY KEY (ID) ENABLE,
    CONSTRAINT TWSS_UUID_POSTS_UQ UNIQUE (UUID),
    CONSTRAINT FK_POSTS FOREIGN KEY (UUID) REFERENCES TWSS_POSTS(UUID)
);

CREATE SEQUENCE TWSS_POSTS_SEQ;
 
CREATE TRIGGER TWSS_POSTS_TRG
BEFORE INSERT ON TWSS_POSTS
FOR EACH ROW
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT TWSS_POSTS_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/