CREATE TABLE TWSS_ATTACHMENTS(
	ID NUMBER NOT NULL,
	UUID VARCHAR2(250 BYTE) NOT NULL,
	TYPE VARCHAR2(250 BYTE) NOT NULL,
	UUID_POST VARCHAR2(250 BYTE) NOT NULL,
	URL VARCHAR2(3000 BYTE) NOT NULL,
    CREATED TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    MODIFIED TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT TWSS_ATTACHMENTS_PK PRIMARY KEY (ID) ENABLE,
    CONSTRAINT TWSS_UUID_ATTACHMENTS_UQ UNIQUE (UUID),
    CONSTRAINT FK_ATTACHMENTS_POSTS FOREIGN KEY (UUID_POST) REFERENCES TWSS_POSTS(UUID)
);

CREATE SEQUENCE TWSS_ATTACHMENTS_SEQ;
 
CREATE TRIGGER TWSS_ATTACHMENTS_TRG
BEFORE INSERT ON TWSS_ATTACHMENTS
FOR EACH ROW
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT TWSS_ATTACHMENTS_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/